name: github-pages

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  # proceso de integración CI (Continuous integration)
  # se hace un analisis de codigo estatico (linting, eslint)
  # pruebas unitarias 
  # pruebas de integración 
  # todo esto podría ser parte del CI 

  # proceso de despliegue:
  # primero se testea y luego se despliega 
  # testing & deploy & send message to discord -> CD
  deploy: # CD
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      
      - name: Installing Dependencies
        run: npm install
      
      - name: Building App
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main